# Declare required additional dependencies
run.deps=org.citrusframework:citrus-camel:4.10.0,\
  org.citrusframework:citrus-testcontainers:4.10.0,\
  org.apache.camel:camel-endpointdsl:4.18.1,\
  org.apache.camel:camel-paho-mqtt5:4.18.1
