# Enable dump of Camel JBang integration output
citrus.camel.jbang.dump.integration.output=true

# Additional dependencies to load
citrus.jbang.dependencies=org.apache.camel:camel-endpointdsl:4.18.1,org.apache.camel:camel-aws2-s3:4.18.1
